namespace ResticGui {

    /**
     * A scheduled backup job: which paths to back up, into which repo,
     * on what cron schedule, and what retention/prune policy to apply
     * afterwards (restic forget --prune).
     */
    public class BackupJob : Object {
        public string id { get; set; }
        public string name { get; set; }
        public string repo_id { get; set; }

        // Paths to back up, newline-free, one per entry.
        public GenericArray<string> source_paths { get; set; }

        // Glob-style excludes, passed as --exclude.
        public GenericArray<string> excludes { get; set; }

        // Standard cron schedule string, e.g. "0 2 * * *". Also used as
        // the source expression for systemd OnCalendar= and Windows
        // Task Scheduler conversions — see SystemdManager / WindowsTaskScheduler.
        public string cron_schedule { get; set; default = "0 2 * * *"; }

        public bool enabled { get; set; default = true; }

        // Retention policy (maps to restic forget flags). -1 means "unset".
        public int keep_last { get; set; default = -1; }
        public int keep_daily { get; set; default = 7; }
        public int keep_weekly { get; set; default = 4; }
        public int keep_monthly { get; set; default = 6; }
        public int keep_yearly { get; set; default = -1; }
        public bool prune_after_forget { get; set; default = true; }

        public BackupJob () {
            source_paths = new GenericArray<string> ();
            excludes = new GenericArray<string> ();
        }

        /**
         * Builds the shell command line that cron will execute for this job.
         * Wraps everything in a small script invocation so env vars (repo
         * password etc.) are sourced from the per-repo env file rather than
         * embedded directly in the crontab line.
         */
        public string build_command (string env_file_path, string log_file_path) {
            var sb = new StringBuilder ();
            sb.append_printf ("/usr/bin/env bash -lc '");
            sb.append_printf ("set -a; source \"%s\"; set +a; ", env_file_path);
            sb.append ("restic backup");
            foreach (var p in source_paths) {
                sb.append_printf (" %s", shell_quote (p));
            }
            foreach (var e in excludes) {
                sb.append_printf (" --exclude %s", shell_quote (e));
            }
            sb.append (" --quiet");

            if (prune_after_forget) {
                sb.append (" && restic forget --prune");
                if (keep_last >= 0) sb.append_printf (" --keep-last %d", keep_last);
                if (keep_daily >= 0) sb.append_printf (" --keep-daily %d", keep_daily);
                if (keep_weekly >= 0) sb.append_printf (" --keep-weekly %d", keep_weekly);
                if (keep_monthly >= 0) sb.append_printf (" --keep-monthly %d", keep_monthly);
                if (keep_yearly >= 0) sb.append_printf (" --keep-yearly %d", keep_yearly);
            }

            sb.append_printf (" >> %s 2>&1", shell_quote (log_file_path));
            sb.append ("'");
            return sb.str;
        }

        /**
         * Builds a fully standalone bash backup script for this job: same
         * backup + forget/prune logic as build_command(), but with the
         * repo's credentials embedded directly rather than sourced from
         * the app's per-repo env file. This makes the script portable —
         * usable from "Export script…", or as the ExecStart of a systemd
         * service — at the cost of the secrets living in the file itself.
         * Callers are responsible for writing it with restrictive (0700)
         * permissions. Linux/macOS only — see build_script_windows() for
         * Windows.
         *
         * `password` is passed in explicitly (rather than read from
         * `repo.password`) so callers are forced to fetch the real,
         * persisted password from the system keyring via SecretManager —
         * `repo.password` is only ever populated transiently while a
         * RepoEditDialog is open in the current session, and is empty
         * for repos freshly loaded from repos.json.
         */
        public string build_script (Repository repo, string password) {
            var sb = new StringBuilder ();
            sb.append ("#!/usr/bin/env bash\n");
            sb.append_printf ("# Generated by restic-gui for job \"%s\".\n", name);
            sb.append ("# Contains your repository password/credentials in plaintext —\n");
            sb.append ("# keep this file private (chmod 0700) and don't commit it anywhere.\n");
            sb.append ("set -euo pipefail\n\n");

            sb.append_printf ("export RESTIC_REPOSITORY=%s\n", shell_quote (repo.location));
            sb.append_printf ("export RESTIC_PASSWORD=%s\n", shell_quote (password));
            repo.env_vars.foreach ((k, v) => {
                sb.append_printf ("export %s=%s\n", k, shell_quote (v));
            });
            sb.append ("\n");

            sb.append ("restic backup");
            foreach (var p in source_paths) {
                sb.append_printf (" %s", shell_quote (p));
            }
            foreach (var e in excludes) {
                sb.append_printf (" --exclude %s", shell_quote (e));
            }
            sb.append (" --quiet\n");

            if (prune_after_forget) {
                sb.append ("restic forget --prune");
                if (keep_last >= 0) sb.append_printf (" --keep-last %d", keep_last);
                if (keep_daily >= 0) sb.append_printf (" --keep-daily %d", keep_daily);
                if (keep_weekly >= 0) sb.append_printf (" --keep-weekly %d", keep_weekly);
                if (keep_monthly >= 0) sb.append_printf (" --keep-monthly %d", keep_monthly);
                if (keep_yearly >= 0) sb.append_printf (" --keep-yearly %d", keep_yearly);
                sb.append ("\n");
            }

            return sb.str;
        }

        /**
         * Windows equivalent of build_script(): a standalone PowerShell
         * script with the repo's credentials embedded as $env: vars.
         * Used by "Export script…" on Windows and by WindowsTaskScheduler
         * as the action a scheduled task runs.
         *
         * `password` is passed in explicitly for the same reason as in
         * build_script() — see that doc comment.
         *
         * If log_path is given, restic's combined output is appended to
         * it (*>>) — used when this runs unattended under Task Scheduler.
         * Pass null for an interactive/export copy where output should
         * just go to the console.
         */
        public string build_script_windows (Repository repo, string password, string? log_path = null) {
            var sb = new StringBuilder ();
            sb.append_printf ("# Generated by restic-gui for job \"%s\".\n", name.replace ("\"", "'"));
            sb.append ("# Contains your repository password/credentials in plaintext —\n");
            sb.append ("# keep this file private and don't commit it anywhere.\n");
            sb.append ("$ErrorActionPreference = 'Stop'\n\n");

            sb.append_printf ("$env:RESTIC_REPOSITORY = %s\n", ps_quote (repo.location));
            sb.append_printf ("$env:RESTIC_PASSWORD = %s\n", ps_quote (password));
            repo.env_vars.foreach ((k, v) => {
                sb.append_printf ("$env:%s = %s\n", k, ps_quote (v));
            });
            sb.append ("\n");

            sb.append ("$resticArgs = @('backup'");
            foreach (var p in source_paths) {
                sb.append_printf (", %s", ps_quote (p));
            }
            foreach (var e in excludes) {
                sb.append_printf (", '--exclude', %s", ps_quote (e));
            }
            sb.append (", '--quiet')\n");
            if (log_path != null) {
                sb.append_printf ("& restic @resticArgs *>> %s\n", ps_quote (log_path));
            } else {
                sb.append ("& restic @resticArgs\n");
            }
            sb.append ("if ($LASTEXITCODE -ne 0) { exit $LASTEXITCODE }\n");

            if (prune_after_forget) {
                sb.append ("\n$forgetArgs = @('forget', '--prune'");
                if (keep_last >= 0) sb.append_printf (", '--keep-last', '%d'", keep_last);
                if (keep_daily >= 0) sb.append_printf (", '--keep-daily', '%d'", keep_daily);
                if (keep_weekly >= 0) sb.append_printf (", '--keep-weekly', '%d'", keep_weekly);
                if (keep_monthly >= 0) sb.append_printf (", '--keep-monthly', '%d'", keep_monthly);
                if (keep_yearly >= 0) sb.append_printf (", '--keep-yearly', '%d'", keep_yearly);
                sb.append (")\n");
                if (log_path != null) {
                    sb.append_printf ("& restic @forgetArgs *>> %s\n", ps_quote (log_path));
                } else {
                    sb.append ("& restic @forgetArgs\n");
                }
            }

            return sb.str;
        }

        private static string shell_quote (string s) {
            return "'" + s.replace ("'", "'\\''") + "'";
        }

        // PowerShell single-quoted string literal: only ' needs escaping,
        // by doubling it — unlike bash, there's no backslash escape inside
        // single quotes.
        private static string ps_quote (string s) {
            return "'" + s.replace ("'", "''") + "'";
        }

        public Json.Node to_json () {
            var obj = new Json.Object ();
            obj.set_string_member ("id", id);
            obj.set_string_member ("name", name);
            obj.set_string_member ("repo_id", repo_id);
            obj.set_string_member ("cron_schedule", cron_schedule);
            obj.set_boolean_member ("enabled", enabled);
            obj.set_int_member ("keep_last", keep_last);
            obj.set_int_member ("keep_daily", keep_daily);
            obj.set_int_member ("keep_weekly", keep_weekly);
            obj.set_int_member ("keep_monthly", keep_monthly);
            obj.set_int_member ("keep_yearly", keep_yearly);
            obj.set_boolean_member ("prune_after_forget", prune_after_forget);

            var paths_arr = new Json.Array ();
            foreach (var p in source_paths) paths_arr.add_string_element (p);
            obj.set_array_member ("source_paths", paths_arr);

            var ex_arr = new Json.Array ();
            foreach (var e in excludes) ex_arr.add_string_element (e);
            obj.set_array_member ("excludes", ex_arr);

            var node = new Json.Node (Json.NodeType.OBJECT);
            node.set_object (obj);
            return node;
        }

        public static BackupJob from_json (Json.Object obj) {
            var job = new BackupJob ();
            job.id = obj.get_string_member ("id");
            job.name = obj.get_string_member ("name");
            job.repo_id = obj.get_string_member ("repo_id");
            job.cron_schedule = obj.get_string_member ("cron_schedule");
            job.enabled = obj.get_boolean_member ("enabled");
            job.keep_last = (int) obj.get_int_member ("keep_last");
            job.keep_daily = (int) obj.get_int_member ("keep_daily");
            job.keep_weekly = (int) obj.get_int_member ("keep_weekly");
            job.keep_monthly = (int) obj.get_int_member ("keep_monthly");
            job.keep_yearly = (int) obj.get_int_member ("keep_yearly");
            job.prune_after_forget = obj.get_boolean_member ("prune_after_forget");

            if (obj.has_member ("source_paths")) {
                var arr = obj.get_array_member ("source_paths");
                arr.foreach_element ((a, i, val) => {
                    job.source_paths.add (val.get_string ());
                });
            }
            if (obj.has_member ("excludes")) {
                var arr = obj.get_array_member ("excludes");
                arr.foreach_element ((a, i, val) => {
                    job.excludes.add (val.get_string ());
                });
            }
            return job;
        }
    }
}
